### ISSUE TITLE
unknown type TH_API on THCUNN.lua:87

### ISSUE THREAD

**Issue by deepcoord** [torch/cunn#425] opened 2017-01-25 17:16 UTC
I saw @soumith has merged some changes into nn and cunn 23 hours ago.
When using ./test.sh, all things are passed except an error: **unknown type TH_API**.

> $ ./test.sh
> Using Lua at:
> /torch/install/bin/lua
> torch loaded succesfully
> nn loaded succesfully
> Running 156 tests
>   1/156 isSetTo ......................................................... [PASS]
> ...
>   156/156 bernoulli ....................................................... [PASS]
> Completed 1247 asserts in 156 tests with 0 failures and 0 errors
> Seed: 	1.4853639167302e+14	
> Running 187 tests
>   1/187 DotProduct ...................................................... [PASS]
> ...
> 187/187 Squeeze ......................................................... [PASS]
> Completed 186453 asserts in 187 tests with 0 failures and 0 errors
> cutorch loaded succesfully
> /work/torch/install/bin/lua: /work/torch/install/share/lua/5.2/cunn/THCUNN.lua:87: unknown type TH_API on line 138
> stack traceback:
> 	[C]: in function 'cdef'
> 	/work/torch/install/share/lua/5.2/cunn/THCUNN.lua:87: in main chunk
> 	[C]: in function 'require'
> 	/work/torch/install/share/lua/5.2/cunn/init.lua:5: in main chunk
> 	[C]: in function 'require'
> 	[C]: in ?

I am now using Nvidia 367.57 and Cuda 8.0.44 on Ubuntu 16.04.

**Comment by soumith** [comment] 2017-01-25 17:17
cc: @pavanky :)

**Comment by pavanky** [comment] 2017-01-25 17:35
Investigating it.

**Comment by pavanky** [comment] 2017-01-25 17:39
@deepcoord @soumith I can't seem to find a `test.sh` file anywhere. If this is a custom file, can you attach it here?

**Comment by soumith** [comment] 2017-01-25 17:40
probably in https://github.com/torch/distro

**Comment by ywu36** [comment] 2017-01-25 17:51
Program completed in 2.07 seconds (pid: 13311).
.../torch/install/share/lua/5.1/cunn/THCUNN.lua:87: declaration specifier expected near 'TH_API' at line 138
stack traceback:
	[C]: in function 'require'
	main-demo-ConvLSTM.lua:9: in main chunk

**Comment by pavanky** [comment] 2017-01-25 17:55
Able to reproduce it. Investigating the cause.

**Comment by pavanky** [comment] 2017-01-25 18:08
@soumith 

I think the issue is caused by the combination of the last two merges. The issue is fixed by reverting either my PR or #421 

Potential causes, the following functions are not generics:
- https://github.com/torch/cunn/blob/master/lib/THCUNN/generic/THCUNN.h#L141
- https://github.com/torch/cunn/blob/master/lib/THCUNN/generic/THCUNN.h#L147

**Comment by soumith** [comment] 2017-01-25 18:17
i've reverted #421, thanks for quickly spotting this. i'll check if master works as well and push new distro commits.

**Closed by soumith** 2017-01-25 18:17 UTC
